# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Actions

on: # 触发条件
  push:
    branches:
      - master

jobs:
  build: # job id
    name: Build and publish # job 名，不写默认使用 job id
    runs-on: ubuntu-latest # 运行环境，可选 ubuntu-latest, ubuntu-18.04, ubuntu-16.04, windows-latest, windows-2019, windows-2016, macOS-latest, macOS-10.14

    steps:
      - uses: actions/checkout@v1 # 拉取博客最新源文件

      - name: Use Node.js 12.x # 指定 Node.js 版本
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Hexo env # 初始构建环境
        run: |
          npm install

      - name: Generate public files # 生成预发布文件
        run: |
          npm run build

      - name: Deploy # 发布
        env:
          GH_REF: ${{ secrets.GH_REF }} # GitHub 仓库地址
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # 预先生成的 GitHub Token
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@d3.js.cn"
          git clone https://${GH_REF} .deploy_git
          cd .deploy_git
          git checkout -B gh-pages
          cd ../
          mv .deploy_git/.git/ ./dist/d3-gallery/
          cd ./dist/d3-gallery/
          git add .
          git commit -m "CI built at `date +"%Y-%m-%d %H:%M:%S"`"
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
